title: Swaraj Khan
description: >
  <div style="text-align: justify">
  
  An ambitious and dynamic candidate deeply passionate about Python programming and proficient in machine learning. Actively pursuing a Bachelor's degree in Computer Science, with a keen focus on enhancing skills in software development, specifically in the domain of machine learning. Eagerly seeking an internship opportunity to apply theoretical knowledge to real-world projects, contribute effectively, and further advance expertise in machine learning techniques.
  
  </div>
theme: jekyll-theme-minimal
website: https://swarajkhan.quarto.pub/swaraj-khan-p/
