title: Swaraj Khan
description: >
  <div style="text-align: justify">
  
  An ambitious and dynamic Computer Science graduate with a strong foundation in Python programming, machine learning, and AI engineering. Experienced in developing agentic LLM systems, retrieval-augmented generation pipelines, and scalable ML infrastructure. Passionate about applying cutting-edge AI techniques to real-world problems and eager to contribute to impactful projects in a fast-paced environment.
  
  </div>
theme: jekyll-theme-minimal
website: https://swarajkhan.quarto.pub/swaraj-khan-p/
