title: Swaraj Khan
description: Highly motivated and enthusiastic individual with a strong passion for Python programming and machine learning. Currently pursuing a Bachelor's degree in Computer Science. Actively seeking an internship opportunity to obtain practical experience, contribute to real-world projects, and advance my skills in software development.
theme: jekyll-theme-minimal
